#Basic content settings
title: Abdul Akbaryeh
name: Abdul Akbaryeh
email: hammado0@yahoo.com
blurb: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at ligula leo. Etiam placerat ac augue in molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin ac varius libero. Integer nec est ac sem ullamcorper vestibulum in ut neque. Morbi a aliquam lorem.</p>"

avatar: ""

nav:
- {name: Blog, url: '#blog'}
- {name: Poems, url: '#poems'}
- {name: About Me, url: '#about-me'}
- {name: Contact, url: '#contact'}

social:
- {url: 'https://facebook.com/', icon: facebook}
- {url: 'https://linkedin.com/', icon: linkedin}
- {url: 'https://yahoo.com/', icon: yahoo}
- {url: 'https://steam.com/', icon: steam}

poems:
- {title: The Hunter's Lust, file: 'poems/poem-1.html'}
- {title: A Soldier against the odds, file: 'poems/poem-2.html'}
- {title: Life's Beauty, file: 'poems/poem-3.html'}
- {title: Into the Rabbit Hole, file: 'poems/poem-4.html'}
